In [34]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.impute import MissingIndicator,SimpleImputer

In [35]:
df=pd.read_csv("Titanic-Dataset.csv",usecols=["Age",'Fare','Survived'])

In [75]:
df

     Survived   Age     Fare
0           0  22.0   7.2500
1           1  38.0  71.2833
2           1  26.0   7.9250
3           1  35.0  53.1000
4           0  35.0   8.0500
..        ...   ...      ...
886         0  27.0  13.0000
887         1  19.0  30.0000
888         0   NaN  23.4500
889         1  26.0  30.0000
890         0  32.0   7.7500

[891 rows x 3 columns]

In [76]:
df.head()

   Survived   Age     Fare
0         0  22.0   7.2500
1         1  38.0  71.2833
2         1  26.0   7.9250
3         1  35.0  53.1000
4         0  35.0   8.0500

In [77]:
X=df.drop(columns=["Survived"])
y=df["Survived"]

In [78]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=2)

In [79]:
X_train.head()

      Age     Fare
30   40.0  27.7208
10    4.0  16.7000
873  47.0   9.0000
182   9.0  31.3875
876  20.0   9.8458

# First we will check without implementing this How much accuracy we will get

In [80]:
si=SimpleImputer(strategy="constant")
X_train_trf=si.fit_transform(X_train)
X_test_trf=si.transform(X_test)

In [81]:
X_train_trf

array([[ 40.    ,  27.7208],
       [  4.    ,  16.7   ],
       [ 47.    ,   9.    ],
       ...,
       [ 71.    ,  49.5042],
       [  0.    , 221.7792],
       [  0.    ,  25.925 ]], shape=(712, 2))

In [82]:
from sklearn.linear_model import LogisticRegression
clf=LogisticRegression()
clf.fit(X_train_trf,y_train)
y_pred=clf.predict(X_test_trf)
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.6201117318435754

In [83]:
mi=MissingIndicator()
X_train_missing=mi.fit_transform(X_train)
X_test_missing=mi.transform(X_test)

In [84]:
X_train["Age_na"]=X_train_missing

In [85]:
X_test["Age_na"]=X_test_missing

In [86]:
X_test

      Age     Fare  Age_na
707  42.0  26.2875   False
37   21.0   8.0500   False
615  24.0  65.0000   False
169  28.0  56.4958   False
68   17.0   7.9250   False
..    ...      ...     ...
89   24.0   8.0500   False
80   22.0   9.0000   False
846   NaN  69.5500    True
870  26.0   7.8958   False
251  29.0  10.4625   False

[179 rows x 3 columns]

In [87]:
from sklearn.impute import SimpleImputer
si=SimpleImputer()

In [88]:
X_train_trf=si.fit_transform(X_train)
X_test_trf=si.transform(X_test)

In [89]:
clf.fit(X_train_trf,y_train)
y_pred=clf.predict(X_test_trf)
accuracy_score(y_pred,y_test)

0.6312849162011173