# Linear Regression ,Ridge and Lesso

In [32]:
# House pricing Dataset
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
columns = [
 'CRIM','ZN','INDUS','CHAS','NOX','RM',
 'AGE','DIS','RAD','TAX','PTRATIO','B','LSTAT','MEDV'
]

df = pd.read_csv(
    r"D:\Data-Science\ML\Regression\Linear Regression\housing.csv",
    header=None,
    names=columns,
    delim_whitespace=True
)
target = df['MEDV']
feature_names = df.drop(columns=[target_name]).columns
pd.DataFrame(df)
df.head()

C:\Users\rohit\AppData\Local\Temp\ipykernel_3508\2101513974.py:11: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  df = pd.read_csv(

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33,36.2

In [34]:
df['price']=target

In [ ]:
df.drop('MEDV',axis=1,inplace=True)

In [42]:
## Dividing the Dataset into independant  and dependant feature
X=df.iloc[:,:-1]# indenpendant feature
y=df.iloc[:,-1]# dependant Feature

In [43]:
X.head()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33

In [50]:
# Lineanr Regression
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import cross_val_score

In [60]:
lin_reg=LinearRegression()
mse=cross_val_score(lin_reg,X,y,scoring='neg_mean_squared_error',cv=5)
mean_mse=np.mean(mse)
print(mean_mse)

-37.13180746769923

In [62]:
# lin_reg.predict(150)

NotFittedError: This LinearRegression instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.

In [65]:
#Ridge Regression
from sklearn.linear_model import Ridge
from sklearn.model_selection import GridSearchCV