In [169]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [170]:
df=pd.read_csv(r"C:\Users\rohit\Downloads\Customers1.csv")

In [171]:
df

    age  gender     review education purchased
0    34  Female       Good        PG       Yes
1    28    Male  Excellent        PG       Yes
2    45  Female       Poor        UG        No
3    52    Male       Good        PG       Yes
4    19  Female  Excellent    School        No
..  ...     ...        ...       ...       ...
93   36    Male       Good        PG       Yes
94   23  Female       Poor    School        No
95   59    Male  Excellent        PG        No
96   32  Female       Good        UG       Yes
97   47    Male       Poor        PG        No

[98 rows x 5 columns]

In [172]:
df=df.iloc[:,1:]

In [173]:
X=df.iloc[:,:-1]

In [174]:
y=df.iloc[:,-1]

In [175]:
y

0     Yes
1     Yes
2      No
3     Yes
4      No
     ...
93    Yes
94     No
95     No
96    Yes
97     No
Name: purchased, Length: 98, dtype: str

In [176]:
from sklearn.model_selection import train_test_split

In [177]:
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=0,test_size=0.2)

In [178]:
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((78, 3), (20, 3), (78,), (20,))

In [179]:
X_train

    gender     review education
43  Female  Excellent    School
62  Female       Poor    School
3     Male       Good        PG
88    Male  Excellent        PG
45  Female       Poor        UG
..     ...        ...       ...
94  Female       Poor    School
67    Male       Good        PG
64  Female       Good        UG
47    Male  Excellent    School
44    Male       Good        PG

[78 rows x 3 columns]

In [180]:
from sklearn.preprocessing import LabelEncoder,OrdinalEncoder,OneHotEncoder
oh=OneHotEncoder()
le=LabelEncoder()
oe=OrdinalEncoder()

In [181]:
from sklearn.compose import ColumnTransformer

ct=ColumnTransformer(
    transformers=[
    ('gender',OneHotEncoder(drop='first', handle_unknown='ignore'),['gender']),
     ('review',OrdinalEncoder(categories=[['Poor','Good','Excellent']]),['review']),
     ('education',OrdinalEncoder(categories=[['School','UG','PG']]),['education'])
     
    ]
    
)

In [182]:
y_train

43    Yes
62     No
3     Yes
88    Yes
45     No
     ...
94     No
67    Yes
64    Yes
47    Yes
44    Yes
Name: purchased, Length: 78, dtype: str

In [183]:
y_train_encoded=le.fit_transform(y_train)
y_test_encoded=le.fit_transform(y_test)

In [184]:
ct.fit(X_train)

ColumnTransformer(transformers=[('gender',
                                 OneHotEncoder(drop='first',
                                               handle_unknown='ignore'),
                                 ['gender']),
                                ('review',
                                 OrdinalEncoder(categories=[['Poor', 'Good',
                                                             'Excellent']]),
                                 ['review']),
                                ('education',
                                 OrdinalEncoder(categories=[['School', 'UG',
                                                             'PG']]),
                                 ['education'])])

In [190]:
X_test_encoded=ct.transform(X_test)
X_train_encoded=ct.transform(X_train)
X_train_encoded

array([[0., 2., 0.],
       [0., 0., 0.],
       [1., 1., 2.],
       [1., 2., 2.],
       [0., 0., 1.],
       [0., 1., 1.],
       [0., 1., 1.],
       [1., 0., 2.],
       [0., 0., 2.],
       [1., 2., 2.],
       [0., 1., 1.],
       [1., 1., 1.],
       [1., 0., 2.],
       [1., 1., 2.],
       [1., 1., 2.],
       [1., 0., 2.],
       [0., 1., 1.],
       [0., 2., 0.],
       [1., 2., 2.],
       [1., 0., 2.],
       [1., 2., 2.],
       [1., 1., 2.],
       [1., 0., 2.],
       [0., 1., 1.],
       [0., 2., 0.],
       [1., 0., 2.],
       [1., 1., 2.],
       [1., 2., 1.],
       [1., 0., 0.],
       [1., 0., 2.],
       [1., 1., 1.],
       [1., 2., 1.],
       [0., 1., 2.],
       [0., 2., 1.],
       [0., 2., 1.],
       [0., 2., 1.],
       [1., 1., 2.],
       [1., 0., 2.],
       [1., 0., 1.],
       [0., 1., 1.],
       [0., 2., 1.],
       [1., 2., 2.],
       [1., 1., 2.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 1., 1.],
       [1., 2., 0.],
       [0., 1., 1.],
       [0., 1., 1.],
       [1., 2., 2.],
       [1., 1., 2.],
       [1., 0., 2.],
       [1., 2., 2.],
       [0., 1., 1.],
       [1., 2., 2.],
       [0., 0., 1.],
       [0., 1., 1.],
       [0., 2., 1.],
       [1., 1., 2.],
       [1., 2., 2.],
       [1., 2., 2.],
       [1., 2., 0.],
       [0., 1., 2.],
       [0., 1., 2.],
       [1., 0., 2.],
       [0., 0., 2.],
       [0., 0., 0.],
       [0., 1., 1.],
       [0., 1., 1.],
       [0., 1., 1.],
       [1., 1., 2.],
       [1., 0., 1.],
       [1., 1., 2.],
       [0., 0., 0.],
       [1., 1., 2.],
       [0., 1., 1.],
       [1., 2., 0.],
       [1., 1., 2.]])

In [186]:
X_train_encoded=pd.DataFrame(X_train_encoded,columns=X_train.columns)

In [187]:
X_test_encoded=pd.DataFrame(X_test_encoded,columns=X_test.columns)

In [188]:
X_test_encoded

    gender  review  education
0      0.0     1.0        0.0
1      0.0     2.0        1.0
2      0.0     0.0        1.0
3      1.0     1.0        2.0
4      0.0     0.0        0.0
5      0.0     1.0        1.0
6      0.0     2.0        1.0
7      0.0     2.0        1.0
8      0.0     0.0        1.0
9      0.0     2.0        1.0
10     1.0     2.0        2.0
11     0.0     0.0        2.0
12     1.0     1.0        2.0
13     1.0     2.0        2.0
14     1.0     2.0        2.0
15     0.0     0.0        0.0
16     0.0     2.0        0.0
17     0.0     1.0        1.0
18     1.0     1.0        2.0
19     0.0     0.0        1.0