In [85]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [86]:
df=pd.read_csv(r"C:\Users\rohit\Downloads\Customers1.csv")

In [87]:
df.sample(10)

    age  gender     review education purchased
80   50  Female       Poor        PG        No
83   29    Male       Poor        UG        No
78   28  Female  Excellent        UG       Yes
73   43    Male       Poor        PG        No
93   36    Male       Good        PG       Yes
33   54    Male       Good        PG       Yes
74   31  Female       Good        UG       Yes
55   42    Male       Good        PG       Yes
49   55    Male       Poor        PG        No
30   20  Female       Poor    School        No

In [88]:
X=df.iloc[:,1:-1]
y=df.iloc[:,-1]

In [89]:
from sklearn.model_selection import train_test_split

In [90]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [91]:
X_train

    gender review education
49    Male   Poor        PG
70  Female   Good        UG
68  Female   Poor    School
15    Male   Poor        PG
39  Female   Good        PG
..     ...    ...       ...
60  Female   Good        UG
71    Male   Good        PG
14  Female   Good        UG
92  Female   Good        UG
51    Male   Good        PG

[78 rows x 3 columns]

In [92]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder

In [93]:
ct=ColumnTransformer(
    transformers=[
        ('gender',OneHotEncoder(drop='first'),['gender']),
        ('review',OrdinalEncoder(categories=[['Poor','Good','Excellent']]),['review']),
        ('education',OrdinalEncoder(categories=[['School','UG','PG']]),['education'])
    ]
)

In [94]:
X_train=ct.fit_transform(X_train)

In [95]:
X_train

array([[1., 0., 2.],
       [0., 1., 1.],
       [0., 0., 0.],
       [1., 0., 2.],
       [0., 1., 2.],
       [1., 1., 2.],
       [1., 1., 2.],
       [0., 0., 2.],
       [1., 1., 2.],
       [1., 0., 2.],
       [1., 1., 2.],
       [0., 0., 0.],
       [0., 2., 1.],
       [1., 2., 2.],
       [1., 0., 2.],
       [0., 0., 1.],
       [1., 2., 2.],
       [1., 0., 2.],
       [0., 2., 1.],
       [0., 2., 1.],
       [0., 2., 1.],
       [1., 2., 2.],
       [1., 1., 2.],
       [1., 0., 2.],
       [1., 2., 2.],
       [1., 1., 1.],
       [1., 2., 2.],
       [1., 2., 2.],
       [1., 2., 2.],
       [0., 1., 1.],
       [1., 1., 2.],
       [1., 1., 2.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 1., 1.],
       [0., 2., 1.],
       [0., 1., 1.],
       [0., 2., 1.],
       [0., 2., 0.],
       [1., 0., 2.],
       [0., 0., 1.],
       [0., 2., 0.],
       [0., 2., 1.],
       [0., 2., 1.],
       [0., 1., 2.],
       [1., 1., 2.],
       [1., 1., 2.],
       [1., 2., 2.],
       [1., 1., 2.],
       [0., 1., 1.],
       [0., 0., 2.],
       [0., 1., 1.],
       [1., 1., 2.],
       [1., 1., 1.],
       [0., 1., 1.],
       [0., 1., 1.],
       [1., 2., 1.],
       [1., 2., 2.],
       [1., 2., 0.],
       [1., 2., 2.],
       [1., 1., 2.],
       [1., 2., 2.],
       [0., 1., 1.],
       [1., 1., 2.],
       [0., 0., 1.],
       [1., 0., 1.],
       [0., 1., 1.],
       [1., 1., 1.],
       [0., 1., 1.],
       [1., 0., 2.],
       [0., 1., 1.],
       [0., 0., 1.],
       [0., 1., 1.],
       [1., 1., 2.],
       [0., 1., 1.],
       [0., 1., 1.],
       [1., 1., 2.]])

In [96]:
X_test=ct.fit_transform(X_test)

In [97]:
X_test

array([[0., 0., 0.],
       [1., 2., 1.],
       [0., 0., 0.],
       [0., 1., 1.],
       [1., 2., 0.],
       [1., 0., 1.],
       [0., 1., 1.],
       [1., 0., 2.],
       [0., 2., 1.],
       [0., 1., 2.],
       [1., 2., 2.],
       [1., 2., 2.],
       [1., 2., 0.],
       [0., 1., 0.],
       [1., 1., 2.],
       [0., 2., 0.],
       [0., 2., 0.],
       [0., 0., 0.],
       [0., 0., 2.],
       [1., 0., 2.]])

In [98]:
from sklearn.preprocessing import LabelEncoder

In [99]:
le=LabelEncoder()

In [100]:
y_train

49     No
70    Yes
68     No
15     No
39    Yes
     ...
60    Yes
71    Yes
14    Yes
92    Yes
51    Yes
Name: purchased, Length: 78, dtype: str

In [101]:
y_train=le.fit_transform(y_train)

In [102]:
y_test=le.fit_transform(y_test)