# Feature-Selection



**Retrival the important features, selecting an important features is very important step before going to ML**

. Droping the constant fetaures ( Regression and classification)

. Information gain (Classification)

· p-value (Regression)

· VIF (Regression)

. Forward selection and backward selection (Regression and classification)

. Correlation with target column ( RegressionIand classification)

# Feature selection method

1. Varience threshold method:
   - based on varience we can decide data is constant or varing
   - Data is not varing not much means, Data has some Value
   - For example we have seen in load_ data set, loan tern : 360
   - Python by default will use varience =0,it will drop those features which are having varience =0
   - varience threshold is hyper Paramerter , we can keep threshold as any value
   - based internal tean discution
   - we will drop those feature which are having <= threshold value
2. P-value :
   - H0: There is is no relation to x and y
   - H1: There is relation X and Y
   -  p<0.05
       -  Reject the Null hypothesis: **Which means do not include the variable**
   -  p>0.05
       - Not reject the Null Hypothesis :  **which means include the variable**
3. Mutual info Classify:
   - KNN and entropy
   - it will give the relation between input and output will pick which are having more relation
   - input vs Output
     - A. Entropy
     - B. KNN
     - C. R-squre: explainability about based on x
4. Forword selecction and backword selection
   
   **Forward selection method**

     - Start with empty set of features

     - Iterate throuh each feature and select the one feature that improves model performance

     - Continue adding fetaures one by one till we meet our creteria

    **Backward selection mehod**

     - Start with full set of features

     - Iterate through each feature by removing the feature which is having less impact on the model
  
     - Continue the process, till your performance is stable

- Both Forward selection and Bcakward selection methods are complex in nature

- More time taken, will avoid in general

5. Variance inflation factor(VIF):

    - VIF will give the analysis of multicollinearity

    - In VIF will find the R-Square value of each input feature wrt to other input fetaure

    - Will keep one fetaure as input and other fetaure are consider as output in Regression equation
  
    - this will keep iterate through all feature
  
    - Every feature behave as input as well as output

    - As we know every regression line give Rsqurae value from that value will fine VIF

    - will drop the feature which are having VIF>5 or VIF > 10 based on iternal team discussion

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [6]:
import pandas as pd
dict1={'A':[100,200,300,400],
'B':[1,2,3,4],
'C':[10,20,30,40],
'D':[10,10,10,10]
      }
df=pd.DataFrame(dict1)

In [7]:
df

     A  B   C   D
0  100  1  10  10
1  200  2  20  10
2  300  3  30  10
3  400  4  40  10

In [10]:
import sklearn

In [11]:
from sklearn. feature_selection import VarianceThreshold
vt=VarianceThreshold(threshold=0)
# Threshold variance value
# we want to drop the feaure based on threshold
# we are finding the variance so only fit
# transform is not required
vt.fit(df)

VarianceThreshold(threshold=0)

In [31]:
dis(vt)

NameError: name 'dis' is not defined

In [29]:
# vt.feature_names_in_
# vt.get_feature_names_out()
# vt.get_params()
# vt.get_support()
# vt.n_features_in_
# vt.threshold
# vt.variances_

array([300.  ,   1.25,  30.  ,   0.  ])

In [32]:
df=pd.read_csv(r"D:\Data-Science\Feature engineering\class\winequality_red.csv")

In [33]:
df

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
1,7.8,0.880,0.00,2.6,0.098,25.0,67.0,0.99680,3.20,0.68,9.8,5
2,7.8,0.760,0.04,2.3,0.092,15.0,54.0,0.99700,3.26,0.65,9.8,5
3,11.2,0.280,0.56,1.9,0.075,17.0,60.0,0.99800,3.16,0.58,9.8,6
4,7.4,0.700,0.00,1.9,0.076,11.0,34.0,0.99780,3.51,0.56,9.4,5
...,...,...,...,...,...,...,...,...,...,...,...,...
1594,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5
1595,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,0.76,11.2,6
1596,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6
1597,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5
1598,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,6

In [36]:
x=df.drop('quality', axis=1)
y=df['quality']

In [38]:
y

0       5
1       5
2       5
3       6
4       5
       ..
1594    5
1595    6
1596    6
1597    5
1598    6
Name: quality, Length: 1599, dtype: int64