# Feature engineering
- so far we have performed featue analysis
   - Data frame quick checks
   - categorical column analysis
   - bar charts,pie charts
   - Nemerical calumn analysis
   - Histogram ,box plots,outliers
   - bi-multi varient analysis
   - correlation etc
- Now we need to learn Freature engineering
   - we will create a new column from better ml model
   - we will perform the  **encoding**,which is convert categorical to numerical data
   - we will do data **transformation**
   - we will perform **scaling: Standartazation and Normalization**
   - we will perform the **missing value analysis**
- simply feature engineering means our data will be modified

In [23]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [24]:
df=pd.read_csv("Visadataset.csv")

# Encoding
- Encoding means convert categorical data into numerical data
- ML/DL or any model only works based on maths
- Model can not understand English characters
- So it is very important to convert categorical label tonumerical values
- for example gender column has two labels
    - Male
    - Female
- Then Female represent as 0 , Male represent  as 1

In [25]:
df["case_status"].unique()

array(['Denied', 'Certified'], dtype=object)

In [26]:
df["case_status"]=df["case_status"].map({"Certified":0,"Denied":1})

In [27]:
df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,1
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,0
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,1
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,1
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,0
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,0
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,0
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.8500,Year,N,0
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,0
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,0

In [28]:
df["continent"].unique()

array(['Asia', 'Africa', 'North America', 'Europe', 'South America',
       'Oceania'], dtype=object)

In [14]:
# pd.get_dummies(df["continent"]).astype(int)

       Africa  Asia  Europe  North America  Oceania  South America
0           0     1       0              0        0              0
1           0     1       0              0        0              0
2           0     1       0              0        0              0
3           0     1       0              0        0              0
4           1     0       0              0        0              0
...       ...   ...     ...            ...      ...            ...
25475       0     1       0              0        0              0
25476       0     1       0              0        0              0
25477       0     1       0              0        0              0
25478       0     1       0              0        0              0
25479       0     1       0              0        0              0

[25480 rows x 6 columns]

In [16]:
# df["continent"]=df["continent"].map({"Africa":0,"Asia":1,"Europe":2,"North America":3,"Oceania":4,"South America":5})

In [30]:
uni=df["continent"].unique()

In [31]:
uni

array(['Asia', 'Africa', 'North America', 'Europe', 'South America',
       'Oceania'], dtype=object)

In [43]:
dic={uni[i] : i for i in range(len(uni))}

In [44]:
dic

{'Asia': 0,
 'Africa': 1,
 'North America': 2,
 'Europe': 3,
 'South America': 4,
 'Oceania': 5}

In [47]:
df["continent"]=df["continent"].map(dic)

In [48]:
df["continent"].unique()

array([0, 1, 2, 3, 4, 5])

In [54]:
df.drop(columns=["continrnt"],axis=1,inplace=True)